//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cinema.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CinemaEntities : DbContext
    {
        public CinemaEntities()
            : base("name=CinemaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Билеты> Билеты { get; set; }
        public virtual DbSet<Бронь> Бронь { get; set; }
        public virtual DbSet<Залы> Залы { get; set; }
        public virtual DbSet<Пользователи> Пользователи { get; set; }
        public virtual DbSet<РазмерыЗалов> РазмерыЗалов { get; set; }
        public virtual DbSet<Сеансы> Сеансы { get; set; }
        public virtual DbSet<СтоимостьБилетов> СтоимостьБилетов { get; set; }
        public virtual DbSet<Фильмы> Фильмы { get; set; }
    }
}
