//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cinema.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Билеты
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Билеты()
        {
            this.Бронь1 = new HashSet<Бронь>();
        }
    
        public int ID { get; set; }
        public Nullable<int> IDСеанса { get; set; }
        public Nullable<int> IDЗала { get; set; }
        public Nullable<int> Ряд { get; set; }
        public Nullable<int> Место { get; set; }
        public Nullable<bool> Бронь { get; set; }
    
        public virtual Залы Залы { get; set; }
        public virtual Сеансы Сеансы { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Бронь> Бронь1 { get; set; }
    }
}
