//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cinema.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Бронь
    {
        public int ID { get; set; }
        public Nullable<int> IDБилета { get; set; }
        public string ФИО { get; set; }
        public string Телефон { get; set; }
    
        public virtual Билеты Билеты { get; set; }
    }
}
