//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cinema.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Сеансы
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Сеансы()
        {
            this.Билеты = new HashSet<Билеты>();
            this.СтоимостьБилетов = new HashSet<СтоимостьБилетов>();
        }
    
        public int ID { get; set; }
        public Nullable<int> IDФильма { get; set; }
        public Nullable<int> IDЗала { get; set; }
        public Nullable<System.DateTime> Дата { get; set; }
        public string Время { get; set; }
        public Nullable<bool> Премьера { get; set; }
        public string Date
        {
            get
            {
                return Дата.Value.ToShortDateString();
            }
            set
            {
                Дата = DateTime.Parse(value);
            }
        }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Билеты> Билеты { get; set; }
        public virtual Залы Залы { get; set; }
        public virtual Фильмы Фильмы { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<СтоимостьБилетов> СтоимостьБилетов { get; set; }
    }
}
