//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cinema.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Фильмы
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Фильмы()
        {
            this.Сеансы = new HashSet<Сеансы>();
        }
    
        public int ID { get; set; }
        public string Название { get; set; }
        public string Жанр { get; set; }
        public string Длительность { get; set; }
        public Nullable<int> Год { get; set; }
        public string Страна { get; set; }
        public string Авторы { get; set; }
        public string Описание { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Сеансы> Сеансы { get; set; }
    }
}
